### ISSUE TITLE
Collaboration with find-similar open source python package

### ISSUE THREAD

**Issue by quillcraftsman** [bent10/find-similar#138]
Hello. 

I didn't find a contact information and decided to create an issue. 

Accidentally I've found this repository and package on JS.
[Our organization](https://github.com/findsimilar) have the same project on python: [find-similar](https://github.com/findsimilar/find-similar). 

May be we can collaborate our efforts? I know it is different languages and If I read the code properly different approaches. But if you are interested in this topic may be we can find some abstract solutions. Please tag me here or [mail me](quilll@craftsman@lol).

**Comment by bent10** [comment]
Thanks for reaching out, I appreciate your interest in collaborating.

I think it might be challenging to collaborate effectively as I'm not well in Python.
